---

- hosts: all
  become: true
  pre_tasks:

  - name: Update Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update CentOS
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu
    apt:
      name:
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install apache and php for CentOS servers
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive:
       src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip/
       dest: /usr/local/bin
       remote_src: yes
       mode: 0755
       owner: root
       group: root

  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
       src: CPE232Gil_HOA7/files/default_html.site
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644